### ISSUE TITLE
https://blockchain.info/q/latesthash response is missing content-length

### ISSUE THREAD

**Issue by ethers** [blockchain/api-v1-client-python#17]
Remote Address:141.101.112.196:443
Request URL:https://blockchain.info/q/latesthash?cors=true
Request Method:GET
Status Code:200 OK

### Response Headers
access-control-allow-origin:*
cf-ray:1f7d4433cd42012c-SJC
content-encoding:gzip
content-language:en
content-security-policy:img-src 'self' data: https://blockchain.info; style-src 'self' 'unsafe-inline'; frame-src 
...

content-length is missing

**Comment by alecalve** [comment]
Unfortunately, Cloudflare does not add a Content-Length header for our API calls as it uses chunked encoding for dynamic content. See [here](https://support.cloudflare.com/hc/en-us/articles/200168386-Why-is-my-dynamic-content-being-sent-with-chunked-encoding-) for a more detailed explanation.
