### ISSUE TITLE
Load API Key.

### ISSUE THREAD

**Issue by Jzarecta** [blockchain/api-v1-client-python#26]
The function shows a construct to include the API, but when I try to do the wallet.signing('account', 'password', '???', 'api-key') 
It doesnt work and get the message:

```
  File "blockchain_pay.py", line 26, in <module>
    print signin.get_balance()
  File "/usr/lib/python2.7/site-packages/blockchain/wallet.py", line 93, in get_balance
    response = util.call_api("merchant/{0}/balance".format(self.identifier), self.build_basic_request())
  File "/usr/lib/python2.7/site-packages/blockchain/util.py", line 27, in call_api
    raise APIException(handle_response(e.read()), e.code)
blockchain.exceptions.APIException: Unknown API Key
```

**Comment by graf23** [comment]
Файл "blockchain_pay.py", строка 26, в <модуль>
    печать signin.get_balance ()
  Файл "/usr/lib/python2.7/site-packages/blockchain/wallet.py", строка 93, в get_balance
    ответ = util.call_api ( "коммерсант / {0} / баланс" .format (self.identifier), self.build_basic_request ())
  Файл "/usr/lib/python2.7/site-packages/blockchain/util.py", строка 27, в call_api
    поднять ApiException (handle_response (e.read ()), e.code)
blockchain.exceptions.APIException: Неизвестный ключ API
