### ISSUE TITLE
Issue with new API (wallet.get_balance())

### ISSUE THREAD

**Issue by fabaff** [blockchain/api-v1-client-python#27]
In January 2016 there were changes in the [Blockchain Wallet API](https://blockchain.info/api/blockchain_wallet_api) which sees to break at least `wallet.get_balance()`.

Can somebody please confirm that this is no longer working?

Original report: https://github.com/balloob/home-assistant/issues/1242

**Comment by tuzzolo** [comment]
Installing and using our local service will resolve this issue: https://github.com/blockchain/service-my-wallet-v3

**Comment by fabaff** [comment]
Using `nodejs` as an intermediary for a Python client is kind of wired and not very user friendly. Beside the introduction of an extra software stack the user has to take care of the server handling. To get the balance of the wallet this looks like overkill even if there is extended security.

As I'm the only one that is complaining about the breakage of the API between versions I will remove that feature because using `blockchain-wallet-service` is not really an option.

**Comment by tuzzolo** [comment]
Are you frequently adding generating new addresses within your wallet? If not, you could simply use get_address or get_unspent_outputs for the addresses you're interested in.
