### ISSUE TITLE
Unknown API key

### ISSUE THREAD

**Issue by minha361** [blockchain/api-v1-client-python#32]
When i test my new api_code 
http://localhost:3000/api/v2/create?password=myPass&api_code=myApiKey
The response is "Unknown API key"
If I use old code it ok 
I check https://blockchain.info/latestblock?api_code=mycode 
The response is "Unknown API key" also

Thanks very much!

**Comment by elizondobanderas** [comment]
I also faces this problem unknown api key

**Comment by jtormey** [comment]
It's possible you're using a Receive Payments API key, which isn't compatible with this API. If you need help with your api key, please reach out to our [awesome support team](https://support.blockchain.com), they can help you.

**Comment by Kadir1993** [comment]
blockhain API key in coinsbank and bitcoin €$

**Comment by Kadir1993** [comment]
10.5000 BTC

**Comment by zoo1199** [comment]
Do I getting helping of blockchain API code

**Comment by zoo1199** [comment]
https://blockchain.info/api #56
