### ISSUE TITLE
python pachage issue

### ISSUE THREAD

**Issue by ziomar1** [blockchain/api-v1-client-python#34]
HI there,

I'm usign the python pachage since a while now. It always worked fine untill this morning.
At the beginnig I received this problem:
ValueError: No JSON object could be decoded 
Then I updated the blockchain wallet python pachage and I start to run a node and I add my local host address to my scrypt.
The local server works fine but now I get this error:
File "/usr/local/lib/python2.7/dist-packages/blockchain/wallet.py", line 119, in list_addresses
    address = Address(a['balance'], a['address'], a['label'], a['total_received'])
KeyError: 'label'

As I said I already updated the pachage and everything possible, please help me to understand how to solve this issue.
This is very important because my site can not receive the clients payment and, as well can not process the payments.

Thank you

**Comment by alecalve** [comment]
The Wallet API can now only be used through [service-my-wallet-v3](https://github.com/blockchain/service-my-wallet-v3). The previous API has been deprecated.

**Comment by alecalve** [comment]
Hi. what version of [service-my-wallet](https://github.com/blockchain/service-my-wallet-v3) and of this API  client are you using?

**Comment by ziomar1** [comment]
Thank you for the quick reply!
I just updated the pachage so I guess the last one, but I'm not sure, could you kindly point me how to check it
Thank you

**Comment by alecalve** [comment]
Thanks, I was able to reproduce the bug and am currently testing a fix. The package should be updated soon.

**Comment by ziomar1** [comment]
great!
I really hope to ear from you soon!

**Comment by alecalve** [comment]
If you are really in a hurry, you can use `pip install git+https://github.com/blockchain/api-v1-client-python.git@missing-address-label` to get a working version of the client. Don't forget to revert to the normal client once the fix is released.

**Comment by ziomar1** [comment]
the main thing is that the label is very importan for my scrypt because it is our client user ID and it is fondamental for our business.
Could you kindly give me and ETA if it is possible

**Comment by alecalve** [comment]
Pypi is currently experiencing [some outage](https://status.python.org/), I can't publish the new release. You can run `pip install git+https://github.com/blockchain/api-v1-client-python.git@v1.3.2` in the meanwhile to upgrade to this new release.

**Comment by ziomar1** [comment]
ok I'll try 
Do I have to change something in the code or it will work with the same command?

Thx

**Comment by alecalve** [comment]
No code change is needed from you

**Comment by ziomar1** [comment]
Yeah it works fine again!
Please just confirm me that now to run my scrypts I need the node to be on, am I right

**Comment by alecalve** [comment]
Yes, you still need to have a running version of [service-my-wallet-v3](https://github.com/blockchain/service-my-wallet-v3)

**Comment by Paiza28** [comment]
Pattanai Sagulrax

**Comment by Paiza28** [comment]
Gmail paiza0047@gmail.com

**Comment by Paiza28** [comment]
ppops
