### ISSUE TITLE
balance NONE

### ISSUE THREAD

**Issue by ziomar1** [blockchain/api-v1-client-python#37]
Hi,

one of the wallets of my app return me for each of the addresses: "balance NONE" and doesn't forward the funds to my hotwallet!
I guess that the problem is that in the wallet there are more than 1500 addresses (more than the limits).
The addresses generation is automatically processed by the app so I really do not know why it allowed, first, to generate more than 1500 addresses and than, after the upgrade of your API, return me the error? 

Due to the fact that there are thousands of addresses I would like to get the private keys of them and split into two different wallets within the quota of 1500.
On your documentations I didn't see how to dump the private key with the python package.

Could you please help me with this issue

Thank you

**Comment by alecalve** [comment]
Hi,

There's no functionality to extract private keys through our APIs, it's possible to do it via a browser console when logged in the web wallet though. You could also transfer the funds to a new wallet via the Python API if you don't wish to keep the same addresses. It may cost you a significant amount in fees if you don't merge addresses.

**Comment by ziomar1** [comment]
Thank you for the quick reply!

The problem is that the web wallet crash because of the too many addresses.
Also can you kindly elaborate where I can get the browser console and how I can dump something like 3000 private keys.
I can not transfer the funds form the Python API because as I said the API return wallet balance NONE  so If I try to transfer the command is not processed!

**Comment by alecalve** [comment]
You can have up to 10,000 addresses if you use an API key and contact support [here](https://support.blockchain.com/hc/en-us/requests/new) to get this new limit.

**Comment by ziomar1** [comment]
But I use the API key already!

this issue is since the new upgade that force me to use the blockchain-wallet-service.
in the blockchain-wallet-service log they shows "error: Number of addresses must be between 1 and 1500"

**Comment by mpfluger** [comment]
There is a feature on the API key that can be activated by support to allow 10k addresses.

**Comment by ziomar1** [comment]
So I have to ask directly to support you can not do from here, am I right?

**Comment by mpfluger** [comment]
Yes, please check with our support team

**Comment by ziomar1** [comment]
thank you I just did!
I hope that the guys from support will be fast as you guys here!

Have a great day
