### ISSUE TITLE
Python client stops working: socket.timeout: timed out

### ISSUE THREAD

**Issue by ziomar1** [blockchain/api-v1-client-python#40]
Hi

my python scrypts gave me these error:
socket.timeout: timed out
the  blockchain-wallet-service, return me this:
1474376078927 - error: Maximum concurrent requests for this endpoint reached. Please try again shortly.
1474376138835 - error: ERR_TIMEOUT

No update from my end, all my scrypts worked fine 24/7 for several months untill few minutes ago.

Pleas help

**Comment by jtormey** [comment]
Closing as this is a duplicate of https://github.com/blockchain/service-my-wallet-v3/issues/136

**Comment by Systemca** [comment]
1VCGjUzuxUFF6FVrnYWEwavXKoDCmtNYB
