### ISSUE TITLE
erlang/elixir official blockchain API library

### ISSUE THREAD

**Issue by 221V** [blockchain/api-v1-client-python#44]
hello!
can i interesting when will be ready erlang/elixir official blockchain API library ?
thanks

**Comment by jtormey** [comment]
We don't have plans for a Erlang/Elixir API library at the moment, so you'll have to make the API calls yourself, see [here](https://blockchain.info/api). You could try using the python library along with something like [ErlPort](https://github.com/hdima/erlport) or [Apache Thrift](https://thrift.apache.org/), but both would probably be more effort than it's worth.
