### ISSUE TITLE
Second password not available in the createWallet API

### ISSUE THREAD

**Issue by ghost** [blockchain/api-v1-client-python#5]
The second password option is not available when creating a wallet using the API

**Comment by Jzarecta** [comment]
I also wonder about this too.

**Comment by alecalve** [comment]
The API client now uses [service-my-wallet-v3](https://github.com/blockchain/service-my-wallet-v3) for all the wallet related calls. Unfortunately, service-my-wallet-v3 does not support second password for wallet creation at the moment.
