### ISSUE TITLE
error when setup over python . after setup what can i do?

### ISSUE THREAD

**Issue by almoharebh** [blockchain/api-v1-client-python#50]
SystemExit was unhandled by user code
Message: usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
#!/usr/bin/env python

from distutils.core import setup

setup(name='blockchain',
      version='1.3.3',
      description='Blockchain API library (v1)',
      author='Blockchain.info',
      author_email='support@blockchain.zendesk.com',
      url='https://github.com/blockchain/api-v1-client-python',
      license='MIT',
      packages=['blockchain', 'blockchain/v2'],
      keywords='blockchain.info api blockchain',
      classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "Intended Audience :: Financial and Insurance Industry",
        "Programming Language :: Python",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.0",
        "Programming Language :: Python :: 3.1",
        "Programming Language :: Python :: 3.2",
        "Programming Language :: Python :: 3.3",
        "Programming Language :: Python :: 3.4",
        "Topic :: Office/Business :: Financial",
        "License :: OSI Approved :: MIT License",
        ],
)

systemexit was unhandled by user code

**Comment by almoharebh** [comment]
![2017-05-07 2](https://cloud.githubusercontent.com/assets/16696115/25777861/376e9a82-32f4-11e7-964a-74a360c18c41.png)
[](url)

**Comment by assafY** [comment]
Hi @almoharebh,

This does not happen on my end. Can you try to install from the command line using `python setup.py install` and let me know if that works?

**Comment by assafY** [comment]
Closing as I cannot reproduce and have not heard back.
