### ISSUE TITLE
methods missing in from blockexplorer 

### ISSUE THREAD

**Issue by PhillRob** [blockchain/api-v1-client-python#51]
Some of the [methods documented](https://github.com/blockchain/api-v1-client-python/blob/master/docs/blockexplorer.md) in are missing (e.g., get_multi_adress, etc.)
```python
dir(blockexplorer)
['Address', 'Block', 'Input', 'InventoryData', 'LatestBlock', 'Output', 'SimpleBlock', 'Transaction', 'UnspentOutput', '__builtins__', '__doc__', '__file__', '__name__', '__package__', 'get_address', 'get_block', 'get_block_height', 'get_blocks', 'get_inventory_data', 'get_latest_block', 'get_tx', 'get_unconfirmed_tx', 'get_unspent_outputs', 'json', 'util']
```

**Comment by assafY** [comment]
Hi @PhillRob,

Thanks, that is correct if you install the package from PyPI - the new methods documented were added to the source code but the new package wasn't published yet.
