### ISSUE TITLE
Unable to create wallet

### ISSUE THREAD

**Issue by ThiruSrinivasan** [blockchain/api-v1-client-python#54]
When I run the following code 

"from blockchain import createwallet
wallet = createwallet.create_wallet('1234password', '58ck39ajuiw', 'http://localhost:8889/', label = 'Test wallet')"

I am getting the following error

.......
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
/Applications/Anaconda/anaconda/lib/python3.6/site-packages/blockchain/util.py in call_api(resource, data, base_url)
     24             payload = payload.encode('UTF-8')
---> 25         response = urlopen(base_url + resource, payload, timeout=TIMEOUT).read()
     26         return handle_response(response)

/Applications/Anaconda/anaconda/lib/python3.6/urllib/request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    222         opener = _opener
--> 223     return opener.open(url, data, timeout)
    224 

/Applications/Anaconda/anaconda/lib/python3.6/urllib/request.py in open(self, fullurl, data, timeout)
    531             meth = getattr(processor, meth_name)
--> 532             response = meth(req, response)
    533 

/Applications/Anaconda/anaconda/lib/python3.6/urllib/request.py in http_response(self, request, response)
    641             response = self.parent.error(
--> 642                 'http', request, response, code, msg, hdrs)
    643 

/Applications/Anaconda/anaconda/lib/python3.6/urllib/request.py in error(self, proto, *args)
    569             args = (dict, 'default', 'http_error_default') + orig_args
--> 570             return self._call_chain(*args)
    571 

/Applications/Anaconda/anaconda/lib/python3.6/urllib/request.py in _call_chain(self, chain, kind, meth_name, *args)
    503             func = getattr(handler, meth_name)
--> 504             result = func(*args)
    505             if result is not None:

/Applications/Anaconda/anaconda/lib/python3.6/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    649     def http_error_default(self, req, fp, code, msg, hdrs):
--> 650         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    651 

HTTPError: HTTP Error 403: Forbidden

**Comment by assafY** [comment]
Hi @ThiruSrinivasan ,

The example you are using contains a mock api key - a valid key is required for creating a waller.

You can request a key here - https://api.blockchain.info/customer/signup

Can you let me know whether you manage to create a wallet using a valid key?
