### ISSUE TITLE
 Block #469703 Returning Key error

### ISSUE THREAD

**Issue by Valansch** [blockchain/api-v1-client-python#55]
The following Code snipped produces a KeyError:
`from blockchain import blockexplorer
blockexplorer.get_block("000000000000000000233013c3823816cc0de0550e83518e10d1304c022a18b1")`

Error:
> Traceback (most recent call last):
  File "bugreport.py", line 4, in <module>
    blockexplorer.get_block("000000000000000000233013c3823816cc0de0550e83518e10d1304c022a18b1")
  File "/usr/local/lib/python2.7/dist-packages/blockchain/blockexplorer.py", line 23, in get_block
    return Block(json_response)
  File "/usr/local/lib/python2.7/dist-packages/blockchain/blockexplorer.py", line 262, in __init__
    self.transactions = [Transaction(t) for t in b['tx']]
  File "/usr/local/lib/python2.7/dist-packages/blockchain/blockexplorer.py", line 238, in __init__
    self.inputs = [Input(i) for i in t['inputs']]
  File "/usr/local/lib/python2.7/dist-packages/blockchain/blockexplorer.py", line 206, in __init__
    self.address = obj['addr']
KeyError: 'addr'

The hash is definitely [valid](https://blockchain.info/block/000000000000000000233013c3823816cc0de0550e83518e10d1304c022a18b1)

<details> 
  <summary>My System:</summary>
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 

[GCC 5.4.0 20160609] on linux2
 
Linux Mint 18.1 (4.4.0-64-generic)
</details>

**Comment by assafY** [comment]
Hi @Valansch,

Well spotted, thanks. If there are multiple inputs in a transaction to the same address, only one contains the address. So for example in the block you mentioned above:

```
{
   "lock_time":0,
   "ver":1,
   "size":581,
   "inputs":[
      {
         "sequence":4294967295,
         "prev_out":{
            "spent":true,
            "tx_index":241675899,
            "type":0,
            "addr":"1BramzjLfrke7bpi6c6ckcudeQTDBQdyC5",
            "value":828485,
            "n":3,
            "script":"76a9147711d5a64372ebd78fc987e9e24bc785aa53e3b488ac"
         },
         "script":"483045022100803360959de92c42a3c5047b799124286bbd068f05bb4c4cf88616f04369cfb102200ed758edd88a7d42d7bfe3f34e3499df0fe2a79616e0f9ea43bb6da06fe4d64e012103f861079972d5de512a921cb3aca2fd1a48cb76a95976deefad52ec3eecb198b0"
      },
      {
         "sequence":4294967295,
         "prev_out":{
            "spent":true,
            "tx_index":241675899,
            "type":0,
            "value":5757,
            "n":1,
            "script":"512103f861079972d5de512a921cb3aca2fd1a48cb76a95976deefad52ec3eecb198b021031f54607b22766572223a312c2276645f736574223a7b22636572745f7572692252ae"
         },
         "script":"0047304402204c494434f45ccfb4ef3cda63dacc0d763320a819b02a6e4a3be6ded7baf4ff1702205412e6f0e8bdaee7f9f624833a9a430c28c1167323ef06b666bc30132423175e01"
      },
      {
         "sequence":4294967295,
         "prev_out":{
            "spent":true,
            "tx_index":241675899,
            "type":0,
            "value":5757,
            "n":0,
```

This transaction was throwing the exception because key 'addr' was not found for every input. If you are using the source code, to fix this you need add `if 'addr' in obj:` before `self.address = obj['addr']` in line 206 of blockexplorer.py.
We will fix this on our end too.

**Comment by assafY** [comment]
This issue is fixed in the latest package.
