### ISSUE TITLE
error  from blockchain import createwallet ImportError: cannot import name createwallet

### ISSUE THREAD

**Issue by justxor** [blockchain/api-v1-client-python#61]
i am trying from blockchain import createwallet. and every time i got the following error     
 from blockchain import createwallet
ImportError: cannot import name createwallet
>>>

**Comment by Bang631** [comment]
My wallet is error.it not work

**Comment by Bang631** [comment]
This is my address/1CK6KHY6MHgYvmRQ4PAafKYDrg1ejb1cE/it can not import every key with every address

**Comment by pors** [comment]
maybe you named the script you run `blockchain.py`?

**Comment by RayXY** [comment]
Sorry I cannot reproduce this issue, please can you make sure your blockchain package is installed correctly.
