### ISSUE TITLE
NameError: name 'basestring' is not defined

### ISSUE THREAD

**Issue by mattisback** [blockchain/api-v1-client-python#62]
It's specified that the libraries are compatible with python 3 but when running:

    bitcoin_summary = blockchain.blockexplorer.get_multi_address(...)

an error is thrown:

```
File "/usr/local/lib/python3.5/dist-packages/blockchain/blockexplorer.py", line 127, in get_multi_address
    if isinstance(addresses, basestring):
NameError: name 'basestring' is not defined    
```

**Comment by bradypittman** [comment]
I think the fix is to change all basestring instances to str as basestring is no longer defined in Python3. That may not fix it, but it is a start

**Comment by Fondor1** [comment]
A quick test on get_balance indicates that replacing instances of basestring with str works fine. I haven't run it through any unit tests however, so I can't guarantee another function isn't broken.

**Comment by code1mountain** [comment]
You can simply fix this by adding this line to the head of the file blockchain/blockexplorer.py:

`from future.utils import string_types as basestring`

This works, because isinstance also allows a list of types. I think this is the easiest solution for that and it doesn't break on python2

**Comment by RayXY** [comment]
there is already a PR on fixing this issue, please direct further comments there https://github.com/blockchain/api-v1-client-python/pull/78
