### ISSUE TITLE
cannot import name 'util'

### ISSUE THREAD

**Issue by whooki3** [blockchain/api-v1-client-python#75]
Hi, I am getting the following error when I run blockexplorer.py
Could anyone point me in the right direction?
This would be very much appreciated!

_Traceback (most recent call last):
  File "C:/Users/Whooki3/AppData/Local/Programs/Python/Python36-32/Lib/site-packages/blockchain/blockexplorer.py", line 6, in <module>
    from . import util
ImportError: cannot import name 'util'

Process finished with exit code 1_

Thanks in advance

**Comment by quimgiraltb** [comment]
I have the same problem... :( Anyone should recommend solutions or examples of python code to run the 'blockchain.blockexplorer' module?

Thanks in advance

**Comment by RayXY** [comment]
`Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "copyright", "credits" or "license()" for more information.
>>> WARNING: The version of Tcl/Tk (8.5.9) in use may be unstable.
Visit http://www.python.org/download/mac/tcltk/ for current information.
from blockchain import blockexplorer
>>> blockexplorer.get_latest_block()
<blockchain.blockexplorer.LatestBlock object at 0x113f5bf98>`

Please see simple usage above. Cannot reproduce the above issue
