### ISSUE TITLE
Recommended way to include API keys in requests

### ISSUE THREAD

**Issue by runt1me** [blockchain/api-v1-client-python#76]
Once issued an API key, what is the recommended way to include it in requests, specifically with the PyPi package? We could just tack it on as a URL parameter (though I don't know the name of the parameter), but it would be nice if this was supported in the PyPi package somehow.

**Comment by RayXY** [comment]
Most of the API functions in our Python libs(1.4) supports an api option parameter as a way to provide your API key. E.g.
https://github.com/blockchain/api-v1-client-python/blob/master/blockchain/blockexplorer.py#L11

The URL parameter is 'api_code' if you are using the HTTP endpoint directly.
